# Generated by Django 4.0.4 on 2022-06-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'employer'), ('candidate', 'candidate')], default='candidate', max_length=120),
        ),
    ]
