# Generated by Django 4.0.4 on 2022-06-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_description',
            field=models.TextField(null=True),
        ),
    ]
