# Generated by Django 4.0.4 on 2022-06-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_alter_applications_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.jobs'),
        ),
    ]
