# Generated by Django 4.0.4 on 2022-06-14 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_alter_applications_job'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applications',
            unique_together={('applicant', 'job')},
        ),
    ]
